### ISSUE TITLE
Need admin access

### ISSUE THREAD

**Issue by chenopis** [kubernetes/kubernetes-docs-ja#15]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
@chenopis and @lucperkins need admin access to this repo so we can setup the Netlify hosting for preview builds.

**Proposed Solution:**
Add @chenopis and @lucperkins to kubernetes-docs-ja-admins group.

**Page to Update:**
https://github.com/orgs/kubernetes/teams/kubernetes-docs-ja-admins/members

**Comment by zacharysarah** [comment]
Granted.

**Comment by tnir** [comment]
@zacharysarah I found kubernetes-docs-ja-admins group didn't have @lucperkins, so adding them to the group.

**Comment by zacharysarah** [comment]
@lucperkins I can’t add you here, either—have you completed your K8s membership request?

**Comment by tnir** [comment]
@chenopis Thanks for your work on Netlify setup on this repo. As it works well now, closing this 😄  /cc @zacharysarah 

/close
