### ISSUE TITLE
admin access request

### ISSUE THREAD

**Issue by nasa9084** [kubernetes/kubernetes-docs-ja#16]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

To manage Projects and branches, I request admin access to k/k-docs-ja repo.

**Proposed Solution:**
add @nasa9084 to kubernetes-docs-ja-admins group.

**Page to Update:**
https://github.com/orgs/kubernetes/teams/kubernetes-docs-ja-admins/members

**Comment by nasa9084** [comment]
I think translation status should be managed using Projects.

https://kubernetes.io/docs/contribute/localization/#project-logistics

**Comment by cstoku** [comment]
@zacharysarah Could you grant `kubernetes-docs-ja` admin to approver of `sig-docs-ja`?(add @nasa9084 and @tnir )
I can't add members because I'm not a Mantainer of `kubernetes-docs-ja-admins` team.

**Comment by zacharysarah** [comment]
@cstoku Done!

**Comment by cstoku** [comment]
Thanks!!
