### ISSUE TITLE
textlintを導入する

### ISSUE THREAD

**Issue by nasa9084** [kubernetes/kubernetes-docs-ja#19]
レビューを正確に、楽に、高速に行うため、textlintである程度の自動レビューを行う。

## 検討事項

* CIツールの選定
    * travisci
    * circleci
    * その他
* 使用するルール

**Comment by nasa9084** [comment]
* https://github.com/azu/textlint-rule-spellcheck-tech-word
* https://github.com/textlint-ja/textlint-rule-no-mix-dearu-desumasu

**Comment by tnir** [comment]
k/websiteが現状Travis CI https://travis-ci.org/kubernetes/website なので、それに合わせておくのがいいかなと思っています。

**Comment by nasa9084** [comment]
私個人としてもtravisは慣れているので、良いと思います!
