### ISSUE TITLE
Hogo server does not work / Deploy preview failed

### ISSUE THREAD

**Issue by zembutsu** [kubernetes/kubernetes-docs-ja#22]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
`hugo server --navigateToChanged` does not work. 

**Proposed Solution:**
I think that some file is missing.
It is necessary to confirm what is missing.

**Page to Update:**
https://kubernetes.io/...

**Comment by zembutsu** [comment]
雑に `content/cn` ディレクトリを戻す PR #23 を作成してしまいましたが、もしかしたら、個別に足りない `.yaml` ファイルを補うほうが良かったりしますでしょうか。

**Comment by zembutsu** [comment]
If hugo check does not pass, test fails for other PRs.

Hugo が動くようにならないと、他の Pull Request を送信してもテストが走らないようなので、対応いただけると助かります。

**Comment by tnir** [comment]
@zembutsu Getting #24 merged would go worse in terms of maintenanceability, I want to use (backport of) kubernetes/website#10219 instead.

（#24 でもCIは動くようになりますが、content/jaに言語非依存のファイルを作成するのは得策ではないと思っています。 kubernetes/website#10219 のバックポートを k/kdocs-ja に取り込むのはいかがでしょう？）

**Comment by tnir** [comment]
@zembutsu kubernetes/website#10219 がスタックしてしまったので、代わりに #27 で解決させていただきました。
