### ISSUE TITLE
Update config.toml for Japanese for /ja/

### ISSUE THREAD

**Issue by tnir** [kubernetes/kubernetes-docs-ja#7]
`https://kubernetes.io/ja/` が構築できるように config.toml に日本語設定を追加する。

from https://kubernetes.slack.com/archives/CAG2M83S8/p1535092377000100

**Comment by nasa9084** [comment]
I have configured on https://github.com/kubernetes-docs-ja/website once, so I will make a PR for this issue.

**Comment by tnir** [comment]
Thanks

/assign @nasa9084

**Comment by tnir** [comment]
/unassign @nasa9084

Closed by #28 

/close
